name: flutter_phpcoin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  #https://pub.dev/packages/get/install 状态管理 路由跳转 国际化翻译 依赖管理
  get: ^4.6.1
  #https://pub.dev/packages/get_storage/install 存储数据 android ios web
  get_storage: ^2.0.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #https://pub.dev/packages/uuid 随机字符串 android ios web
  uuid: ^3.0.6
  #https://pub.dev/packages/mime/versions html类型转换 android ios web
  mime: ^1.0.1
  #https://pub.dev/packages/html  html文本  android ios web
  html: ^0.15.0
  #https://pub.dev/packages/flutter_launcher_icons#-installing-tab- 自动在线生成logo图标 android ios
  flutter_launcher_icons: ^0.9.2
  #https://pub.dev/packages/flutter_native_splash#-example-tab-  解决启动白屏 android ios web
  flutter_native_splash: ^2.1.2+1
  #https://pub.dev/packages/tab_indicator_styler/install 指示器  android ios
  tab_indicator_styler: ^2.0.0
  #https://pub.flutter-io.cn/packages/fluttertoast/install 吐司弹窗 android ios web
  fluttertoast: ^8.0.9
  # https://pub.dev/packages/dio 网络请求  android ios web
  dio: ^4.0.6
  #https://pub.dev/packages/dio_cache_interceptor/install http缓存管理 android ios web
  dio_cache_interceptor: ^3.2.6
  #https://pub.dev/packages/cookie_jar 缓存 android ios web
  cookie_jar: ^3.0.1
  #https://pub.dev/packages/dio_cookie_manager#-installing-tab- http缓存 android ios web
  dio_cookie_manager: ^2.0.0
  #https://pub.dev/packages/date_format#-installing-tab- 时间格式转换  android ios web
  date_format: ^2.0.5

  #https://pub.dev/packages/card_swiper/install 导航图
  card_swiper: ^2.0.3
  #https://pub.dev/packages/pull_to_refresh 下拉刷新 android ios web
  pull_to_refresh: ^2.0.0
  #https://pub.dev/packages/flutter_html  加载html内容 android ios
  flutter_html: ^2.2.1

  #https://pub.dev/packages/device_info  查看设备信息 android ios
  device_info_plus: ^3.2.2

  # https://pub.dev/packages/extended_image/install 图片  android ios web
  extended_image: ^6.0.2+1
  #https://pub.dev/packages/flutter_rating_bar/install 星星
  flutter_rating_bar: ^4.0.0
  #https://pub.dev/packages/flutter_spinkit  加载进度 android ios web
  flutter_spinkit: ^5.1.0
  #https://pub.dev/packages/connectivity#-installing-tab-  监听网络状态  android ios web
  connectivity: ^3.0.6

  #https://pub.dev/packages/package_info#-installing-tab-  包名信息 android ios
  package_info: ^2.0.2
  #https://pub.dev/packages/video_player 视频播放  android ios web
  video_player: ^2.3.0
  #https://pub.dev/packages/open_file  打开文件插件 android ios
  open_file: ^3.2.1
  #https://pub.dev/packages/path_provider#-installing-tab- 获取文件存储路径  android ios
  path_provider: ^2.0.9

  #https://pub.dev/packages/animator#-installing-tab- 动画效果 android ios web
  animator: ^3.1.0
  #https://pub.dev/packages/flutter_slidable#-installing-tab- 侧滑组件 android ios web
  flutter_slidable: ^0.6.0
  #https://pub.dev/packages/marquee/versions 跑马灯 android ios web
  marquee: ^2.2.1
  #https://pub.dev/packages/audioplayers 声音播放 android ios web
  audioplayers: ^0.20.1
  #https://pub.dev/packages/flutter_advanced_switch/install 切换按钮
  flutter_advanced_switch: ^3.0.0
  #https://pub.dev/packages/webview_flutter#-installing-tab-    加载在线html android ios
  webview_flutter: ^2.8.0
  #https://pub.dev/packages/floor 数据库 flutter packages pub run build_runner build flutter packages pub run build_runner watch android ios
  floor: ^1.2.0
  #https://pub.dev/packages/photo_view#-installing-tab- 可伸缩图片 android ios web
  photo_view: ^0.13.0
  #https://pub.dev/packages/share#-installing-tab- 内置分享图片文本 android ios
  share: ^2.0.4
  #https://pub.dev/packages/image_cropper 图片裁剪 android ios
  image_cropper: ^1.5.0
  #https://pub.dev/packages/flutter_picker#-installing-tab- 选择弹窗 android ios web
  flutter_picker: ^2.0.3
  #https://pub.dev/packages/qr_flutter 二维码生成  android ios web
  qr_flutter: ^4.0.0
  #https://pub.dev/packages/permission_handler 请求权限 android ios
  permission_handler: ^8.3.0
  #https://pub.dev/packages/url_launcher 打开外部应用  android ios web
  url_launcher: ^6.0.18
  #https://pub.dev/packages/flutter_vibrate 震动 android ios
  flutter_vibrate: ^1.3.0
  #https://pub.dev/packages/image_picker/install 选择图片视频 android ios web
  image_picker: ^0.8.4+11
  #https://pub.dev/packages/flutter_screenutil 屏幕适配 android ios web
  flutter_screenutil: ^5.3.1

  #https://pub.dev/packages/image_gallery_saver 图片保存到本地 android ios
  image_gallery_saver: ^1.7.1
  #https://pub.dev/packages/animated_bottom_navigation_bar/install 底部选项卡
  animated_bottom_navigation_bar: ^0.3.2

  #https://pub.dev/packages/percent_indicator/install 进度条指示器
  percent_indicator: ^4.0.0
  #https://pub.dev/packages/flutter_qr_reader#-installing-tab- 二维码扫描 android ios
  flutter_qr_reader: ^1.0.5
  #https://pub.dev/packages/logger/install 日志输出  android ios web
  logger: ^1.1.0
  #https://pub.dev/packages/flutter_image_compress#-installing-tab-  图片压缩  android ios
  flutter_image_compress: ^1.1.0
  #https://pub.dev/packages/image_downloader#-installing-tab- 图片下载器 android ios
  image_downloader: ^0.31.0
  #https://pub.dev/packages/liquid_progress_indicator/install 加载进度 android ios web
  liquid_progress_indicator: ^0.4.0
  #https://pub.dev/packages/flutter_flavor/install 不同环境 风格
  flutter_flavor: ^3.0.3
  #https://pub.dev/packages/animated_digit/install 数字滚动
  animated_digit: ^3.1.3
  #https://pub.dev/packages/flutter_easyloading/install 进度条
  flutter_easyloading: ^3.0.3
  #https://pub.dev/packages/basic_utils/install
  basic_utils: ^4.2.0
  #https://pub.dev/packages/fast_base58/install
  fast_base58: ^0.2.1
  #https://pub.dev/packages/encrypt/install
  encrypt: ^5.0.1
  #https://pub.dev/packages/hash/install
  hash: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0
  build_runner: ^2.1.2
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
#生成logo图标  命令行： flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path_android: "assets/icon/iconRound.png"
  image_path_ios: "assets/icon/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"


#生成启动背景图  命令行：flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/bg/startBg.png
  color: "#687bed"
  android: true
  android_disable_fullscreen: true
  web: false
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/raw/
    - assets/icon/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
